export type QuoteCategory = "GOGGINS" | "STOIC" | "DRIFT" | "SIGMA";

export type Quote = {
  text: string;
  category: QuoteCategory;
  attribution?: string;
};

export const QUOTES: Quote[] = [
  // ---------- GOGGINS ----------
  { text: "Stay hard.", category: "GOGGINS", attribution: "David Goggins" },
  { text: "When you think you're done, you're only at 40 percent of your capacity.", category: "GOGGINS", attribution: "David Goggins" },
  { text: "Most people quit when their mind starts whispering. The mind whispers because it's afraid you'll listen.", category: "GOGGINS" },
  { text: "Suffering is the truest test of who you are.", category: "GOGGINS" },
  { text: "Nobody is coming to save you. Get up.", category: "GOGGINS" },
  { text: "Comfort is a slow poison.", category: "GOGGINS" },
  { text: "You will never beat me. You will literally have to kill me.", category: "GOGGINS", attribution: "David Goggins" },
  { text: "The only way you gain mental toughness is to do things you're not happy doing.", category: "GOGGINS", attribution: "David Goggins" },
  { text: "Motivation is a fleeting visitor. Discipline is the friend who never leaves.", category: "GOGGINS" },
  { text: "If it's hard, do it. If it's easy, you're already losing.", category: "GOGGINS" },
  { text: "The pain you feel today is the strength you'll feel tomorrow.", category: "GOGGINS" },
  { text: "Callus your mind.", category: "GOGGINS", attribution: "David Goggins" },
  { text: "Greatness is reserved for those willing to be uncomfortable longer than everyone else.", category: "GOGGINS" },
  { text: "Don't stop when you're tired. Stop when you're done.", category: "GOGGINS" },
  { text: "Your dreams are just on the other side of one more rep.", category: "GOGGINS" },
  { text: "We live in an external world. The war is internal.", category: "GOGGINS" },
  { text: "Average is a place that gets crowded the moment you stop running.", category: "GOGGINS" },
  { text: "Excuses are the architecture of mediocrity.", category: "GOGGINS" },
  { text: "The cave you fear to enter holds the version of you that you swore you'd become.", category: "GOGGINS" },
  { text: "Hard work cures. Run.", category: "GOGGINS" },
  { text: "You don't owe anyone a comfortable version of yourself.", category: "GOGGINS" },
  { text: "Discomfort is the price. Pay it daily.", category: "GOGGINS" },
  { text: "The only person in your way is the one in the mirror.", category: "GOGGINS" },
  { text: "Pain is data. Listen, log it, move.", category: "GOGGINS" },
  { text: "If your goals don't scare you, they aren't goals. They're chores.", category: "GOGGINS" },
  { text: "You become unstoppable the day you stop bargaining with the version of you that wants to quit.", category: "GOGGINS" },
  { text: "There is no finish line. Only the next mile.", category: "GOGGINS" },
  { text: "Rest is a tool, not a destination.", category: "GOGGINS" },
  { text: "Your competition is the version of you from yesterday morning.", category: "GOGGINS" },
  { text: "The world rewards those who refuse to flinch.", category: "GOGGINS" },

  // ---------- STOIC ----------
  { text: "You have power over your mind, not outside events. Realize this, and you will find strength.", category: "STOIC", attribution: "Marcus Aurelius" },
  { text: "The impediment to action advances action. What stands in the way becomes the way.", category: "STOIC", attribution: "Marcus Aurelius" },
  { text: "Waste no more time arguing what a good man should be. Be one.", category: "STOIC", attribution: "Marcus Aurelius" },
  { text: "If it is not right, do not do it. If it is not true, do not say it.", category: "STOIC", attribution: "Marcus Aurelius" },
  { text: "We suffer more in imagination than in reality.", category: "STOIC", attribution: "Seneca" },
  { text: "Luck is what happens when preparation meets opportunity.", category: "STOIC", attribution: "Seneca" },
  { text: "He who fears death will never do anything worthy of a man who is alive.", category: "STOIC", attribution: "Seneca" },
  { text: "It is not the man who has too little, but the man who craves more, that is poor.", category: "STOIC", attribution: "Seneca" },
  { text: "First say to yourself what you would be, then do what you have to do.", category: "STOIC", attribution: "Epictetus" },
  { text: "No man is free who is not master of himself.", category: "STOIC", attribution: "Epictetus" },
  { text: "Wealth consists not in having great possessions, but in having few wants.", category: "STOIC", attribution: "Epictetus" },
  { text: "The chief task in life is simply this: to identify and separate matters so that I can say clearly which are external and not in my control.", category: "STOIC", attribution: "Epictetus" },
  { text: "Difficulties strengthen the mind, as labor does the body.", category: "STOIC", attribution: "Seneca" },
  { text: "Begin at once to live, and count each separate day as a separate life.", category: "STOIC", attribution: "Seneca" },
  { text: "It is the power of the mind to be unconquerable.", category: "STOIC", attribution: "Seneca" },
  { text: "How much trouble he avoids who does not look to see what his neighbor says or does.", category: "STOIC", attribution: "Marcus Aurelius" },
  { text: "Do every act of your life as if it were your last.", category: "STOIC", attribution: "Marcus Aurelius" },
  { text: "Confine yourself to the present.", category: "STOIC", attribution: "Marcus Aurelius" },
  { text: "Death smiles at us all. All we can do is smile back.", category: "STOIC", attribution: "Marcus Aurelius" },
  { text: "If you are distressed by anything external, the pain is not due to the thing itself, but to your estimate of it.", category: "STOIC", attribution: "Marcus Aurelius" },
  { text: "Man conquers the world by conquering himself.", category: "STOIC", attribution: "Zeno" },
  { text: "Hardship makes the man.", category: "STOIC" },
  { text: "Memento mori. You will die. So live.", category: "STOIC" },
  { text: "Amor fati. Love what comes. Then bend it.", category: "STOIC" },
  { text: "The cucumber is bitter. Throw it away. There are brambles in the path. Step aside. That's all.", category: "STOIC", attribution: "Marcus Aurelius" },
  { text: "Choose not to be harmed and you won't feel harmed. Don't feel harmed and you haven't been.", category: "STOIC", attribution: "Marcus Aurelius" },
  { text: "Receive without pride, let go without attachment.", category: "STOIC", attribution: "Marcus Aurelius" },
  { text: "You could leave life right now. Let that determine what you do, say and think.", category: "STOIC", attribution: "Marcus Aurelius" },
  { text: "How ridiculous and how strange to be surprised at anything that happens in life.", category: "STOIC", attribution: "Marcus Aurelius" },
  { text: "Time is the most valuable thing a man can spend.", category: "STOIC", attribution: "Theophrastus" },

  // ---------- DRIFT ----------
  { text: "The corner does not care if you are afraid.", category: "DRIFT" },
  { text: "Speed is honest. Everything else negotiates.", category: "DRIFT" },
  { text: "If you're not sideways, you're not committed.", category: "DRIFT" },
  { text: "The line is a suggestion. The throttle is a contract.", category: "DRIFT" },
  { text: "Engine on. Doubt off.", category: "DRIFT" },
  { text: "Late nights, low rpm dreams.", category: "DRIFT" },
  { text: "Tokyo at 3 a.m. doesn't owe you an explanation.", category: "DRIFT" },
  { text: "Lift off and you lose. Stay flat and you fly.", category: "DRIFT" },
  { text: "Tires only scream when they're working.", category: "DRIFT" },
  { text: "Fear coasts. Will accelerates.", category: "DRIFT" },
  { text: "The road remembers cowards. So drive like it doesn't.", category: "DRIFT" },
  { text: "There is no autopilot for the life you actually want.", category: "DRIFT" },
  { text: "Every red line is a sermon.", category: "DRIFT" },
  { text: "If the wheel is straight, the lesson is over.", category: "DRIFT" },
  { text: "Smoke is just confidence becoming visible.", category: "DRIFT" },
  { text: "Headlights forward. Past in the mirror. Mirror small for a reason.", category: "DRIFT" },
  { text: "Your apex is not your enemy's apex.", category: "DRIFT" },
  { text: "You don't outrun gravity. You befriend it.", category: "DRIFT" },
  { text: "Under-steer is a question. Over-steer is the answer.", category: "DRIFT" },
  { text: "The gas pedal is a confession.", category: "DRIFT" },
  { text: "Cold start. Hot mind.", category: "DRIFT" },
  { text: "There's a version of you doing 140 right now. Catch up.", category: "DRIFT" },
  { text: "Neon doesn't ask permission.", category: "DRIFT" },
  { text: "Chase the sound, not the score.", category: "DRIFT" },
  { text: "Some doors only open at full throttle.", category: "DRIFT" },
  { text: "Tail out, eyes up.", category: "DRIFT" },
  { text: "Fuel is finite. Spend it like it knows.", category: "DRIFT" },
  { text: "The garage is honest. The freeway is fair. The track is a verdict.", category: "DRIFT" },
  { text: "Loud pipes save no one. But they tell the truth.", category: "DRIFT" },
  { text: "Drift like you're disappointed in your past self.", category: "DRIFT" },

  // ---------- SIGMA ----------
  { text: "He who reads at 5 a.m. fears no recession.", category: "SIGMA" },
  { text: "Be the asset, not the option.", category: "SIGMA" },
  { text: "Networking is for people who can't compound alone.", category: "SIGMA" },
  { text: "Quiet is leverage. Use it.", category: "SIGMA" },
  { text: "The lone wolf logs in early.", category: "SIGMA" },
  { text: "Cold showers. Colder eyes.", category: "SIGMA" },
  { text: "If they can't reach you, they can't slow you.", category: "SIGMA" },
  { text: "Read history. Lift heavy. Speak less.", category: "SIGMA" },
  { text: "Replies are taxes. Pay only what's necessary.", category: "SIGMA" },
  { text: "Comparison is a leak. Plug it.", category: "SIGMA" },
  { text: "The grindset is just compounding with a haircut.", category: "SIGMA" },
  { text: "Notifications off. Outcomes on.", category: "SIGMA" },
  { text: "Most rooms are theater. Find the workshop.", category: "SIGMA" },
  { text: "Skills compound silently. Status decays loudly.", category: "SIGMA" },
  { text: "You don't need a tribe. You need a craft.", category: "SIGMA" },
  { text: "The man who reads 30 books a year is in a different country.", category: "SIGMA" },
  { text: "Solitude is not loneliness. It's the rent for greatness.", category: "SIGMA" },
  { text: "Be the kind of busy that doesn't need an audience.", category: "SIGMA" },
  { text: "Your competitors are scrolling. You're not.", category: "SIGMA" },
  { text: "Speak when paid. Build when not.", category: "SIGMA" },
  { text: "Energy is currency. Audit your spend.", category: "SIGMA" },
  { text: "The internet is loud. Your mission is quiet. Match it.", category: "SIGMA" },
  { text: "If they wanted you, they'd act like it. If you wanted it, you'd build it.", category: "SIGMA" },
  { text: "Dopamine is borrowed. Discipline is owned.", category: "SIGMA" },
  { text: "The man with one calendar beats the man with five inboxes.", category: "SIGMA" },
  { text: "Your future is a function of what you don't open.", category: "SIGMA" },
  { text: "Strangers in coffee shops won't fund your dreams. Get back to work.", category: "SIGMA" },
  { text: "Closed mouth. Open notebook.", category: "SIGMA" },
  { text: "There is no algorithm for the man who refuses to be seen until he's ready.", category: "SIGMA" },
  { text: "The reps you skip are the regrets you keep.", category: "SIGMA" },
];

export function pickRandomQuote(exclude?: number): { quote: Quote; index: number } {
  if (QUOTES.length === 0) throw new Error("Quote pool empty");
  if (QUOTES.length === 1) return { quote: QUOTES[0], index: 0 };
  let idx = Math.floor(Math.random() * QUOTES.length);
  if (exclude !== undefined && idx === exclude) {
    idx = (idx + 1) % QUOTES.length;
  }
  return { quote: QUOTES[idx], index: idx };
}
